"""update users tables

Revision ID: 0a6e5cdffd49
Revises: 8be1f59b0723
Create Date: 2023-08-02 22:46:55.776313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6e5cdffd49'
down_revision = '8be1f59b0723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
