"""create jobs and applications tables

Revision ID: 8be1f59b0723
Revises: 24a0ec21ded0
Create Date: 2023-08-02 13:51:24.888841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8be1f59b0723'
down_revision = '24a0ec21ded0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('support_mail', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('funding', sa.String(), nullable=True),
    sa.Column('size', sa.Enum('UNDER_50', 'UNDER_100', 'UNDER_500', 'OVER_1000', name='companysize'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('industry_role', sa.String(), nullable=True),
    sa.Column('industries', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cv', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('current_earnings', sa.String(), nullable=True),
    sa.Column('desired_earnings', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_industries', 'candidate_profiles', ['industries'], unique=False, postgresql_using='gin')
    op.create_index('ix_candidate_skills', 'candidate_profiles', ['industries'], unique=False, postgresql_using='gin')
    op.add_column('companies', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('secret_key', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('owner_id', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('files_url', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_unique_constraint(None, 'companies', ['slug'])
    op.create_unique_constraint(None, 'companies', ['secret_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'files_url')
    op.drop_column('companies', 'owner_id')
    op.drop_column('companies', 'secret_key')
    op.drop_column('companies', 'slug')
    op.drop_index('ix_candidate_skills', table_name='candidate_profiles', postgresql_using='gin')
    op.drop_index('ix_candidate_industries', table_name='candidate_profiles', postgresql_using='gin')
    op.drop_table('candidate_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
