"""update clients profile

Revision ID: 94d88b024507
Revises: a5046c7992bb
Create Date: 2023-08-05 07:00:31.216236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d88b024507'
down_revision = 'a5046c7992bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'client_profiles', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_profiles', type_='foreignkey')
    op.drop_column('client_profiles', 'company_id')
    # ### end Alembic commands ###
