"""create user clients profile

Revision ID: a5046c7992bb
Revises: 9a3ae597a68a
Create Date: 2023-08-05 06:55:49.612965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5046c7992bb'
down_revision = '9a3ae597a68a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_profiles_company_id_fkey', 'client_profiles', type_='foreignkey')
    op.drop_column('client_profiles', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_profiles_company_id_fkey', 'client_profiles', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
