"""updated audit logs column

Revision ID: de43b4230279
Revises: ab758d4d6208
Create Date: 2023-08-03 01:42:19.846605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de43b4230279'
down_revision = 'ab758d4d6208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
